name: Deploy Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run tests
      run: |
        # Add your test commands here
        echo "Running tests..."
        python -m pytest --version || echo "No tests configured yet"
    
    - name: Check Flask app
      run: |
        cd flask_app
        python -c "import app; print('Flask app imports successfully')"
  
  build-docs:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mkdocs mkdocs-material
    
    - name: Generate static documentation
      run: |
        # Convert markdown files to a static site structure
        mkdir -p docs-site
        cp README.md docs-site/index.md
        cp EXECUTIVE_SUMMARY.md docs-site/
        cp -r analysis docs-site/
        cp -r docs docs-site/documentation
        
        # Create a simple index for GitHub Pages
        echo "# Xt-EHR T7.2 Sub-team for Imaging Reports Model" > docs-site/README.md
        echo "" >> docs-site/README.md
        echo "## Documentation" >> docs-site/README.md
        echo "- [Project Overview](index.md)" >> docs-site/README.md
        echo "- [Executive Summary](EXECUTIVE_SUMMARY.md)" >> docs-site/README.md
        echo "- [Analysis Results](analysis/)" >> docs-site/README.md
        echo "- [Documentation](documentation/)" >> docs-site/README.md
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-site
        
  # Optional: Deploy to other platforms
  # deploy-railway:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Deploy to Railway
  #     run: |
  #       # Railway deployment commands would go here
  #       echo "Railway deployment not configured yet"
  
  # deploy-render:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Deploy to Render
  #     run: |
  #       # Render deployment commands would go here
  #       echo "Render deployment not configured yet"